const COLOR_THEMES = {
    // 主題 1: 預設 (SCA) - 精品咖啡協會官方色系
    default: {
        name: "Default",
        palette: {
            // Layer 1 - 主要分類 (基於官方風味輪配色)
            "fruity": "#e74c3c",
            "floral": "#e8c0cb",
            "sour": "#f1c40f",
            "green_vegetative": "#2ecc71",
            "sweet": "#f4d03f",
            "nutty_cocoa": "#d4905a",
            "spices": "#c4714f",
            "roasted": "#8b6f47",
            "papery_musty": "#95a5a6",
            "other": "#7f8c8d",

            // Layer 2 & 3 - 水果 (紅色系)
            "berry": "#e74c3c",
            "blueberry": "#3498db",
            "raspberry": "#e91e63",
            "blackberry": "#9c27b0",
            "strawberry": "#e74c3c",
            "dried_fruit": "#cd5c5c",
            "raisin": "#8b4513",
            "prune": "#6a4423",
            "citrus_fruit": "#f1c40f",
            "lemon": "#f4d03f",
            "lime": "#2ecc71",
            "orange": "#e67e22",
            "grapefruit": "#ff6b6b",
            "other_fruit": "#e74c3c",
            "apple": "#dc2d1d",
            "peach": "#e8957e",
            "apricot": "#ffb347",
            "pear": "#d4a574",
            "pineapple": "#ffd700",
            "passion_fruit": "#ffc300",
            "cherry": "#c71585",
            "pomegranate": "#a71930",
            "grape": "#7851a9",
            "coconut": "#e6d5c3",

            // Layer 2 & 3 - 花香 (粉紅紫色系)
            "rose": "#e8c0cb",
            "jasmine": "#f5bde6",
            "chamomile": "#f4e5d3",
            "lemongrass": "#d4e157",
            "osmanthus": "#ffb74d",
            "orange_blossom": "#ffb74d",
            "lavender": "#b39ddb",
            "hibiscus": "#ec407a",

            // Layer 2 & 3 - 酸味 (黃色系)
            "fermented": "#f1c40f",
            "winey": "#c49c63",
            "fermented_taste": "#e6b89a",
            "alcohol": "#d4734f",
            "sour_aromatics": "#f4d03f",
            "acetic_acid": "#ffe66d",
            "butyric_acid": "#f0ad4e",
            "citric_acid": "#fcb900",
            "isovaleric_acid": "#e8960f",
            "malic_acid": "#ff9800",
            "overripe_underripe": "#f1c40f",
            "overripe": "#f4a46f",
            "under_ripe": "#cde4b0",
            "peapod": "#2ecc71",

            // Layer 2 & 3 - 綠色/蔬菜 (綠色系)
            "fresh": "#2ecc71",
            "dark_green": "#27ae60",
            "vegetative": "#52be80",
            "hay_like": "#82c9a3",
            "herb_like": "#58d68d",
            "olive_oil": "#3d8b40",

            // Layer 2 & 3 - 甜感 (金色/米色系)
            "brown_sugar": "#daa520",
            "caramelized": "#f4d03f",
            "honey": "#ffd700",
            "molasses": "#8b4513",
            "maple_syrup": "#d2691e",
            "brown_sugar_taste": "#cd853f",
            "vanilla": "#f5deb3",
            "vanilla_flavor": "#ffe4b5",
            "vanillin": "#ffe7be",
            "overall_sweet": "#f4d03f",
            "sweet_aromatics": "#f4d8a8",

            // Layer 2 & 3 - 堅果/可可 (褐色系)
            "nutty": "#d4905a",
            "almond": "#cd853f",
            "hazelnut": "#a0826d",
            "peanuts": "#8b6f47",
            "cocoa": "#6f4e37",
            "cocoa_flavor": "#704f38",
            "dark_chocolate": "#3d2817",
            "chocolate": "#6f4f38",

            // Layer 2 & 3 - 香料 (棕紅色系)
            "brown_spice": "#c4714f",
            "cinnamon": "#d97f4f",
            "nutmeg": "#8b4513",
            "clove": "#5c3317",
            "anise": "#a0826d",
            "pepper": "#8b6f47",

            // Layer 2 & 3 - 烘焙 (深棕色系)
            "cereal": "#c9a965",
            "grain": "#d4a574",
            "malt": "#8b6f47",
            "brown_roast": "#6f4e37",
            "smoky": "#5c4033",
            "ashy": "#8b8680",
            "tobacco": "#704f38",
            "pipe_tobacco": "#5c3317",
            "tobacco_flavor": "#4d3c27",

            // Layer 2 & 3 - 紙味/霉味 (灰色系)
            "stale": "#95a5a6",
            "cardboard": "#a9a59f",
            "papery": "#b8b4ac",
            "moldy_damp": "#7f8c8d",
            "musty_dusty": "#95a5a6",
            "musty_earthy": "#8b7e6b",
            "woody": "#8b6f47",

            // Layer 2 & 3 - 其他 (多色系)
            "black_tea": "#6f4e37",
            "phenolic": "#c4714f",
            "bitter": "#7f8c8d",
            "salty": "#95a5a6",
            "medicinal": "#a9a59f",
            "petroleum": "#34495e",
            "meaty_brothy": "#8b6f47",
            "animalic": "#7f6946",
            "acrid": "#e74c3c",
            "burnt": "#5c4033",
            "pungent": "#8b4513",
            "rubbery": "#5c3a1a",
            "kunkry": "#4d3c27",
            "raw": "#dc2d1d",
            "beany": "#f1c40f",
            "chemical": "#34495e"
        }
    },

    // 主題 2: Catppuccin Latte - 冷調現代風格
    catppuccin: {
        name: "貓布奇諾拿鐵 (Catppuccin Latte)",
        palette: {
            // Layer 1 - 主要分類
            "fruity": "#d20f39",
            "floral": "#ea76cb",
            "sour": "#179299",
            "green_vegetative": "#40a02b",
            "sweet": "#d4af37",
            "nutty_cocoa": "#fe640b",
            "spices": "#8c4001",
            "roasted": "#d5597b",
            "papery_musty": "#7c7f93",
            "other": "#6c6f86",

            // Layer 2 & 3 - 水果
            "berry": "#d81b60",
            "blueberry": "#5e60ba",
            "raspberry": "#d20f39",
            "blackberry": "#9c2d54",
            "strawberry": "#e64980",
            "dried_fruit": "#d81b60",
            "raisin": "#8c3f50",
            "prune": "#6a2d42",
            "citrus_fruit": "#dfa612",
            "lemon": "#f4d35e",
            "lime": "#a8d5ba",
            "orange": "#fe640b",
            "grapefruit": "#f0ad4e",
            "other_fruit": "#d20f39",
            "apple": "#d81b60",
            "peach": "#fe640b",
            "apricot": "#fe640b",
            "pear": "#d4af37",
            "pineapple": "#f4d35e",
            "passion_fruit": "#dfa612",
            "cherry": "#d20f39",
            "pomegranate": "#c2185b",
            "grape": "#7b2cbf",
            "coconut": "#a8d5ba",

            // Layer 2 & 3 - 花香
            "rose": "#ea76cb",
            "jasmine": "#f5bde6",
            "chamomile": "#f2d5cf",
            "lemongrass": "#a6e3a1",
            "osmanthus": "#fab387",
            "orange_blossom": "#f9e2af",
            "lavender": "#b4befe",
            "hibiscus": "#f38ba8",

            // Layer 2 & 3 - 酸味
            "fermented": "#179299",
            "winey": "#8ecae6",
            "fermented_taste": "#457b9d",
            "alcohol": "#1d3557",
            "sour_aromatics": "#dfa612",
            "acetic_acid": "#f4d35e",
            "butyric_acid": "#ee964b",
            "citric_acid": "#f0ad4e",
            "isovaleric_acid": "#e76f51",
            "malic_acid": "#d62828",
            "overripe_underripe": "#dfa612",
            "overripe": "#d4af37",
            "under_ripe": "#a8d5ba",
            "peapod": "#40a02b",

            // Layer 2 & 3 - 綠色/蔬菜
            "fresh": "#40a02b",
            "dark_green": "#2d6a4f",
            "vegetative": "#52b788",
            "hay_like": "#95b8d1",
            "herb_like": "#b7e4c7",
            "olive_oil": "#95b8d1",

            // Layer 2 & 3 - 甜感
            "brown_sugar": "#d4af37",
            "caramelized": "#f4d35e",
            "honey": "#ffd60a",
            "molasses": "#d9680f",
            "maple_syrup": "#fe640b",
            "brown_sugar_taste": "#d4af37",
            "vanilla": "#f2d5cf",
            "vanilla_flavor": "#fcd5ce",
            "vanillin": "#f7d8d3",
            "overall_sweet": "#d4af37",
            "sweet_aromatics": "#f5bde6",

            // Layer 2 & 3 - 堅果/可可
            "nutty": "#fe640b",
            "almond": "#fed049",
            "hazelnut": "#d8955c",
            "peanuts": "#8c4001",
            "cocoa": "#8c4001",
            "cocoa_flavor": "#704030",
            "dark_chocolate": "#4a2511",
            "chocolate": "#6f4e37",

            // Layer 2 & 3 - 香料
            "brown_spice": "#8c4001",
            "cinnamon": "#d9680f",
            "nutmeg": "#c1666b",
            "clove": "#8c4001",
            "anise": "#d4a574",
            "pepper": "#c1666b",

            // Layer 2 & 3 - 烘焙
            "cereal": "#d4af37",
            "grain": "#f4d35e",
            "malt": "#d9680f",
            "brown_roast": "#8c4001",
            "smoky": "#5a4a42",
            "ashy": "#7c7f93",
            "tobacco": "#6c6f86",
            "pipe_tobacco": "#5c5f78",
            "tobacco_flavor": "#4c4f6a",

            // Layer 2 & 3 - 紙味/霉味
            "stale": "#7c7f93",
            "cardboard": "#9b9faf",
            "papery": "#7c7f93",
            "moldy_damp": "#5a5d72",
            "musty_dusty": "#4c4f6a",
            "musty_earthy": "#5c5f78",
            "woody": "#6c6f86",

            // Layer 2 & 3 - 其他
            "black_tea": "#1e66f5",
            "phenolic": "#8c3f50",
            "bitter": "#6c6f86",
            "salty": "#7c7f93",
            "medicinal": "#5a5d72",
            "petroleum": "#4c4f6a",
            "meaty_brothy": "#8c4001",
            "animalic": "#6f4e37",
            "acrid": "#d20f39",
            "burnt": "#8c3f50",
            "pungent": "#c1666b",
            "rubbery": "#5a5d72",
            "kunkry": "#4c4f6a",
            "raw": "#d20f39",
            "beany": "#fe640b",
            "chemical": "#1e66f5"
        }
    },

    // 主題 3: Gruvbox Dark - 溫暖對比強烈
    gruvbox: {
        name: "格魯夫盒深色 (Gruvbox Dark)",
        palette: {
            // Layer 1 - 主要分類
            "fruity": "#fb4934",
            "floral": "#fe8019",
            "sour": "#fabd2f",
            "green_vegetative": "#b8bb26",
            "sweet": "#d4af37",
            "nutty_cocoa": "#d3869b",
            "spices": "#8ec07c",
            "roasted": "#d65d0e",
            "papery_musty": "#928374",
            "other": "#a89984",

            // Layer 2 & 3 - 水果
            "berry": "#fb4934",
            "blueberry": "#83a598",
            "raspberry": "#fb4934",
            "blackberry": "#8f3f71",
            "strawberry": "#fe8019",
            "dried_fruit": "#d3869b",
            "raisin": "#a89984",
            "prune": "#928374",
            "citrus_fruit": "#fabd2f",
            "lemon": "#f4d35e",
            "lime": "#b8bb26",
            "orange": "#fe8019",
            "grapefruit": "#fabd2f",
            "other_fruit": "#fb4934",
            "apple": "#fb4934",
            "peach": "#fe8019",
            "apricot": "#fe8019",
            "pear": "#fabd2f",
            "pineapple": "#f4d35e",
            "passion_fruit": "#fabd2f",
            "cherry": "#fb4934",
            "pomegranate": "#d3869b",
            "grape": "#8ec07c",
            "coconut": "#b8bb26",

            // Layer 2 & 3 - 花香
            "rose": "#d3869b",
            "jasmine": "#fe8019",
            "chamomile": "#fabd2f",
            "lemongrass": "#b8bb26",
            "osmanthus": "#fe8019",
            "orange_blossom": "#fabd2f",
            "lavender": "#d3869b",
            "hibiscus": "#fb4934",

            // Layer 2 & 3 - 酸味
            "fermented": "#b8bb26",
            "winey": "#fabd2f",
            "fermented_taste": "#fe8019",
            "alcohol": "#d65d0e",
            "sour_aromatics": "#fabd2f",
            "acetic_acid": "#f4d35e",
            "butyric_acid": "#fe8019",
            "citric_acid": "#fabd2f",
            "isovaleric_acid": "#d65d0e",
            "malic_acid": "#fb4934",
            "overripe_underripe": "#b8bb26",
            "overripe": "#8ec07c",
            "under_ripe": "#b8bb26",
            "peapod": "#b8bb26",

            // Layer 2 & 3 - 綠色/蔬菜
            "fresh": "#b8bb26",
            "dark_green": "#8ec07c",
            "vegetative": "#689d6a",
            "hay_like": "#83a598",
            "herb_like": "#8ec07c",
            "olive_oil": "#b8bb26",

            // Layer 2 & 3 - 甜感
            "brown_sugar": "#d4af37",
            "caramelized": "#fabd2f",
            "honey": "#f4d35e",
            "molasses": "#d65d0e",
            "maple_syrup": "#fe8019",
            "brown_sugar_taste": "#d4af37",
            "vanilla": "#fabd2f",
            "vanilla_flavor": "#fe8019",
            "vanillin": "#f4d35e",
            "overall_sweet": "#d4af37",
            "sweet_aromatics": "#fabd2f",

            // Layer 2 & 3 - 堅果/可可
            "nutty": "#d3869b",
            "almond": "#8f3f71",
            "hazelnut": "#a89984",
            "peanuts": "#928374",
            "cocoa": "#8f3f71",
            "cocoa_flavor": "#704030",
            "dark_chocolate": "#4a2511",
            "chocolate": "#6f4e37",

            // Layer 2 & 3 - 香料
            "brown_spice": "#d65d0e",
            "cinnamon": "#fe8019",
            "nutmeg": "#d3869b",
            "clove": "#a89984",
            "anise": "#fabd2f",
            "pepper": "#fb4934",

            // Layer 2 & 3 - 烘焙
            "cereal": "#fabd2f",
            "grain": "#f4d35e",
            "malt": "#fe8019",
            "brown_roast": "#d65d0e",
            "smoky": "#928374",
            "ashy": "#a89984",
            "tobacco": "#8f3f71",
            "pipe_tobacco": "#704030",
            "tobacco_flavor": "#6f4e37",

            // Layer 2 & 3 - 紙味/霉味
            "stale": "#928374",
            "cardboard": "#a89984",
            "papery": "#928374",
            "moldy_damp": "#7c6f64",
            "musty_dusty": "#928374",
            "musty_earthy": "#a89984",
            "woody": "#8f3f71",

            // Layer 2 & 3 - 其他
            "black_tea": "#83a598",
            "phenolic": "#d3869b",
            "bitter": "#928374",
            "salty": "#a89984",
            "medicinal": "#8f3f71",
            "petroleum": "#704030",
            "meaty_brothy": "#a89984",
            "animalic": "#928374",
            "acrid": "#fb4934",
            "burnt": "#d65d0e",
            "pungent": "#fe8019",
            "rubbery": "#8f3f71",
            "kunkry": "#704030",
            "raw": "#fb4934",
            "beany": "#fabd2f",
            "chemical": "#83a598"
        }
    }
};