// js/localization.js
// 應用程式所有 UI 文本的本地化字典
window.LOCALIZATION = {
    "zh": {
        "app_title": "風味輪筆記",
        "coffee_button": "☕ 咖啡",
        "luxury_button": "💎 奢華",
        "tea_button": "🍵 茶",
        "lang_zh_button": "中", // 語言按鈕本身不需本地化，但為保持一致性仍列出
        "lang_en_button": "EN",
        "lang_jp_button": "日",
        "theme_default_button": "🎨 預設",
        "theme_catppuccin_button": "🎨 Catppuccin",
        "theme_gruvbox_button": "🎨 Gruvbox",
        "theme_luxury_gold_button": "⚜️ 奢華金",
        "theme_rose_gold_button": "🌹 玫瑰金",
        "theme_platinum_button": "💍 鉑金",
        "theme_tea_spring_button": "🌱 春日茶園",
        "theme_tea_autumn_button": "🍂 秋日焙茶",
        "theme_tea_midnight_button": "🌙 靜夜沉思",
        "selected_flavors_title": "選取風味列表",
        "no_flavors_selected": "尚未選取任何風味...",
        "generate_note_title": "生成筆記",
        "output_mode_list": "1️⃣ 純風味文字",
        "output_mode_note": "2️⃣ 社群分享模式",
        "output_mode_ai_prompt": "🤖 AI 品評提示詞",
        "copy_button": "📋 複製到剪貼簿",
        "share_button": "🔗 分享文字 (Web Share API)",
        "share_image_button": "分享專屬圖卡",
        "settings_title": "筆記設定與自訂風味",
        "origin_label": "品名 / 產區 (Origin)",
        "origin_placeholder": "e.g. 衣索比亞 耶加雪菲",
        "add_custom_flavor_heading": "手動新增自訂風味",
        "custom_flavor_name_label": "風味名稱 (將用於筆記)",
        "custom_flavor_name_placeholder": "e.g. 七里香、九層塔",
        "select_category_label": "選擇類別 (決定順序)",
        "select_category_default": "-- 請選擇 Layer 1 大類別 --",
        "add_custom_flavor_button": "➕ 新增自訂風味",
        "click_to_select_flavor": "點擊選擇風味",
        "copy_success": "複製成功!",
        "copy_success_short": "✅ 已複製",
        "copy_fail": "複製失敗!",
        "share_fail": "分享失敗",
        "flavor_added_alert": "已加入筆記!",
        "flavor_added": "已加入",
        "select_finer_flavor": "請點選更細項的風味",
        "layer1_category_label": "大類別",
        "coffee_drink_type": "咖啡",
        "tea_drink_type": "茶",
        "flavor_wheel_module_error": "FlavorWheel 模組未載入。請檢查 js/flavorWheel.js。",
        "loading_data": "正在載入風味資料...",
        "data_load_success": "資料載入成功。",
        "data_load_fail": "載入 JSON 資料失敗:",
        "failed_to_load_coffee": "Failed to load coffee_data.json:",
        "ai_friendly_header": "[風味輪筆記輸出]\n",
        "ai_friendly_drink": "飲料",
        "ai_friendly_origin": "產區",
        "ai_friendly_flavors": "風味",
        "reset_flavors_button": "重設列表",
        "voice_start_instruction": "請開始說話描述風味...",
        "voice_stop_instruction": "再次點擊按鈕可結束辨識",
        "voice_listening_title": "正在聆聽中..."
    },
    "en": {
        "app_title": "Flavor Wheel Note",
        "coffee_button": "☕ Coffee",
        "luxury_button": "💎 Luxury",
        "tea_button": "🍵 Tea",
        "lang_zh_button": "中",
        "lang_en_button": "EN",
        "lang_jp_button": "日",
        "theme_default_button": "🎨 Default",
        "theme_catppuccin_button": "🎨 Catppuccin",
        "theme_gruvbox_button": "🎨 Gruvbox",
        "theme_luxury_gold_button": "⚜️ Luxury Gold",
        "theme_rose_gold_button": "🌹 Rose Gold",
        "theme_platinum_button": "💍 Platinum",
        "theme_tea_spring_button": "🌱 Spring Garden",
        "theme_tea_autumn_button": "🍂 Autumn Roast",
        "theme_tea_midnight_button": "🌙 Midnight",
        "selected_flavors_title": "Selected Flavors",
        "no_flavors_selected": "No flavors selected yet...",
        "generate_note_title": "Generate Note",
        "output_mode_list": "1️⃣ Plain Text List",
        "output_mode_note": "2️⃣ Social/Note Mode",
        "output_mode_ai_prompt": "🤖 AI Tasting Prompt",
        "copy_button": "📋 Copy to Clipboard",
        "share_button": "🔗 Share Text (Web Share API)",
        "share_image_button": "Share Image Card",
        "settings_title": "Note Settings & Custom Flavors",
        "origin_label": "Origin / Name",
        "origin_placeholder": "e.g. Ethiopia Yirgacheffe",
        "add_custom_flavor_heading": "Manually Add Custom Flavor",
        "custom_flavor_name_label": "Flavor Name (for note)",
        "custom_flavor_name_placeholder": "e.g. Jasmine, Basil",
        "select_category_label": "Select Category (for order)",
        "select_category_default": "-- Select Layer 1 Category --",
        "add_custom_flavor_button": "➕ Add Custom Flavor",
        "click_to_select_flavor": "Click to select flavor",
        "copy_success": "Copied successfully!",
        "copy_success_short": "✅ Copied!",
        "copy_fail": "Failed to copy!",
        "share_fail": "Share failed",
        "flavor_added_alert": " has been added to your note!",
        "flavor_added": "Added",
        "select_finer_flavor": "Please select a more specific flavor",
        "layer1_category_label": "Category",
        "coffee_drink_type": "Coffee",
        "tea_drink_type": "Tea",
        "flavor_wheel_module_error": "FlavorWheel module not loaded. Please check js/flavorWheel.js.",
        "loading_data": "Loading flavor data...",
        "data_load_success": "Data loaded successfully.",
        "data_load_fail": "Failed to load JSON data:",
        "failed_to_load_coffee": "Failed to load coffee_data.json:",
        "ai_friendly_header": "[Flavor Wheel Note Output]\n",
        "ai_friendly_drink": "Drink",
        "ai_friendly_origin": "Origin",
        "ai_friendly_flavors": "Flavors",
        "reset_flavors_button": "Reset List",
        "voice_start_instruction": "Start speaking to describe flavors...",
        "voice_stop_instruction": "Click again to stop recognition",
        "voice_listening_title": "Listening..."
    },
    "jp": {
        "app_title": "フレーバーホイールノート",
        "coffee_button": "☕ コーヒー",
        "luxury_button": "💎 贅沢",
        "tea_button": "🍵 お茶",
        "lang_zh_button": "中",
        "lang_en_button": "EN",
        "lang_jp_button": "日",
        "theme_default_button": "🎨 デフォルト",
        "theme_catppuccin_button": "🎨 Catppuccin",
        "theme_gruvbox_button": "🎨 Gruvbox",
        "theme_luxury_gold_button": "⚜️ 豪華ゴールド",
        "theme_rose_gold_button": "🌹 ローズゴールド",
        "theme_platinum_button": "💍 プラチナ",
        "theme_tea_spring_button": "🌱 春の茶園",
        "theme_tea_autumn_button": "🍂 秋の焙じ茶",
        "theme_tea_midnight_button": "🌙 静夜の瞑想",
        "selected_flavors_title": "選択された風味リスト",
        "no_flavors_selected": "まだ風味は選択されていません...",
        "generate_note_title": "ノートを生成",
        "output_mode_list": "1️⃣ 純粋な風味テキスト",
        "output_mode_note": "2️⃣ ソーシャル/ノートモード",
        "output_mode_ai_prompt": "🤖 AIテイスティングプロンプト",
        "copy_button": "📋 クリップボードにコピー",
        "share_button": "🔗 テキスト共有 (Web Share API)",
        "share_image_button": "画像カードを共有",
        "settings_title": "ノート設定とカスタム風味",
        "origin_label": "銘柄 / 産地 (Origin)",
        "origin_placeholder": "例: エチオピア イルガチェフェ",
        "add_custom_flavor_heading": "手動でカスタム風味を追加",
        "custom_flavor_name_label": "風味名 (ノートに使用)",
        "custom_flavor_name_placeholder": "例: ジャスミン、バジル",
        "select_category_label": "カテゴリを選択 (順序決定)",
        "select_category_default": "-- レイヤー1カテゴリを選択 --",
        "add_custom_flavor_button": "➕ カスタム風味を追加",
        "click_to_select_flavor": "風味を選択するにはクリック",
        "copy_success": "コピーしました!",
        "copy_success_short": "✅ コピー済み",
        "copy_fail": "コピーに失敗しました!",
        "share_fail": "共有に失敗しました",
        "flavor_added_alert": "がノートに追加されました!",
        "flavor_added": "追加済み",
        "select_finer_flavor": "より詳細な風味を選択してください",
        "layer1_category_label": "大分類",
        "coffee_drink_type": "コーヒー",
        "tea_drink_type": "お茶",
        "flavor_wheel_module_error": "FlavorWheel モジュールがロードされていません。js/flavorWheel.js を確認してください。",
        "loading_data": "風味データをロード中...",
        "data_load_success": "データロード成功。",
        "data_load_fail": "JSONデータのロードに失敗しました:",
        "failed_to_load_coffee": "Failed to load coffee_data.json:",
        "ai_friendly_header": "[フレーバーホイールノート出力]\n",
        "ai_friendly_drink": "飲み物",
        "ai_friendly_origin": "産地",
        "ai_friendly_flavors": "風味",
        "reset_flavors_button": "リストをリセット",
        "voice_start_instruction": "フレーバーを話してください...",
        "voice_stop_instruction": "もう一度クリックして停止",
        "voice_listening_title": "聞き取り中..."
    }
};